// Full gallery map per couple (auto-generated from public/wedding-stories)
const storyImageMap = {
  "Akshita-sourav": [
    "public/wedding-stories/Akshita-sourav/images%202/AS_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_013.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_09.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_10.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_11.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_12.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/020.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/021.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/033.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/1.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/1.webp",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/10.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/11.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/12.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/13.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/14.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/16.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/18.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/19.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/2.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/20.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/21.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/22.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/3.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/31.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/32.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/33.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/34.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/35.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/36.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/37.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/38.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/39.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/4.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/5.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/6.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/7.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/8.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/9.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/051.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/059.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/069.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/52.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/53.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/54.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/55.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/56.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/57.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/58.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/59.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/60.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/61.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/62.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/63.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/64.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/65.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/66.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/67.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/68.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/70.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/71.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/72.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/73.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/74.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/75.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/76.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/77.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/78.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/79.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/80.jpeg"
  ],
  "malkit-harman": [
    "public/wedding-stories/malkit-harman/000001.jpeg",
    "public/wedding-stories/malkit-harman/0001.jpeg",
    "public/wedding-stories/malkit-harman/0016.jpeg",
    "public/wedding-stories/malkit-harman/01.jpeg",
    "public/wedding-stories/malkit-harman/016.jpeg",
    "public/wedding-stories/malkit-harman/039.jpeg",
    "public/wedding-stories/malkit-harman/10.jpeg",
    "public/wedding-stories/malkit-harman/11.jpeg",
    "public/wedding-stories/malkit-harman/12.jpeg",
    "public/wedding-stories/malkit-harman/13.jpeg",
    "public/wedding-stories/malkit-harman/14.jpeg",
    "public/wedding-stories/malkit-harman/15.jpeg",
    "public/wedding-stories/malkit-harman/16.jpeg",
    "public/wedding-stories/malkit-harman/17.jpeg",
    "public/wedding-stories/malkit-harman/18.jpeg",
    "public/wedding-stories/malkit-harman/19.jpeg",
    "public/wedding-stories/malkit-harman/2.jpeg",
    "public/wedding-stories/malkit-harman/20.jpeg",
    "public/wedding-stories/malkit-harman/21.jpeg",
    "public/wedding-stories/malkit-harman/22.jpeg",
    "public/wedding-stories/malkit-harman/23.jpeg",
    "public/wedding-stories/malkit-harman/24.jpeg",
    "public/wedding-stories/malkit-harman/25.jpeg",
    "public/wedding-stories/malkit-harman/26.jpeg",
    "public/wedding-stories/malkit-harman/27.jpeg",
    "public/wedding-stories/malkit-harman/28.jpeg",
    "public/wedding-stories/malkit-harman/29.jpeg",
    "public/wedding-stories/malkit-harman/3.jpeg",
    "public/wedding-stories/malkit-harman/31.jpeg",
    "public/wedding-stories/malkit-harman/32.jpeg",
    "public/wedding-stories/malkit-harman/33.jpeg",
    "public/wedding-stories/malkit-harman/34.jpeg",
    "public/wedding-stories/malkit-harman/35.jpeg",
    "public/wedding-stories/malkit-harman/36.jpeg",
    "public/wedding-stories/malkit-harman/37.jpeg",
    "public/wedding-stories/malkit-harman/38.jpeg",
    "public/wedding-stories/malkit-harman/39.jpeg",
    "public/wedding-stories/malkit-harman/4.jpeg",
    "public/wedding-stories/malkit-harman/40.jpeg",
    "public/wedding-stories/malkit-harman/41.jpeg",
    "public/wedding-stories/malkit-harman/43.jpeg",
    "public/wedding-stories/malkit-harman/44.jpeg",
    "public/wedding-stories/malkit-harman/5.jpeg",
    "public/wedding-stories/malkit-harman/7.jpeg",
    "public/wedding-stories/malkit-harman/8.jpeg",
    "public/wedding-stories/malkit-harman/9.jpeg",
    "public/wedding-stories/malkit-harman/90.jpeg"
  ],
  "partham-tamanna": [
    "public/wedding-stories/partham-tamanna/013.jpeg",
    "public/wedding-stories/partham-tamanna/1.jpeg",
    "public/wedding-stories/partham-tamanna/11.jpeg",
    "public/wedding-stories/partham-tamanna/12.jpeg",
    "public/wedding-stories/partham-tamanna/13.jpeg",
    "public/wedding-stories/partham-tamanna/15.jpeg",
    "public/wedding-stories/partham-tamanna/16.jpeg",
    "public/wedding-stories/partham-tamanna/18.jpeg",
    "public/wedding-stories/partham-tamanna/19.jpeg",
    "public/wedding-stories/partham-tamanna/2.jpeg",
    "public/wedding-stories/partham-tamanna/20.jpeg",
    "public/wedding-stories/partham-tamanna/21.jpeg",
    "public/wedding-stories/partham-tamanna/22.jpeg",
    "public/wedding-stories/partham-tamanna/23.jpeg",
    "public/wedding-stories/partham-tamanna/24.jpeg",
    "public/wedding-stories/partham-tamanna/25.jpeg",
    "public/wedding-stories/partham-tamanna/26.jpeg",
    "public/wedding-stories/partham-tamanna/27.jpeg",
    "public/wedding-stories/partham-tamanna/28.jpeg",
    "public/wedding-stories/partham-tamanna/29.jpeg",
    "public/wedding-stories/partham-tamanna/3.jpeg",
    "public/wedding-stories/partham-tamanna/30.jpeg",
    "public/wedding-stories/partham-tamanna/31.jpeg",
    "public/wedding-stories/partham-tamanna/32.jpeg",
    "public/wedding-stories/partham-tamanna/33.jpeg",
    "public/wedding-stories/partham-tamanna/35.jpeg",
    "public/wedding-stories/partham-tamanna/36.jpeg",
    "public/wedding-stories/partham-tamanna/37.jpeg",
    "public/wedding-stories/partham-tamanna/38.jpeg",
    "public/wedding-stories/partham-tamanna/39.jpeg",
    "public/wedding-stories/partham-tamanna/4.jpeg",
    "public/wedding-stories/partham-tamanna/5.jpeg",
    "public/wedding-stories/partham-tamanna/6.jpeg"
  ],
  "punit-varsha": [
    "public/wedding-stories/punit-varsha/PV%20(1).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(10).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(11).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(12).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(13).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(14).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(15).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(16).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(2).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(3).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(4).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(5).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(6).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(7).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(8).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(9).jpeg"
  ],
  "Samkit": [
    "public/wedding-stories/Samkit/1.jpeg",
    "public/wedding-stories/Samkit/10.jpeg",
    "public/wedding-stories/Samkit/11.jpeg",
    "public/wedding-stories/Samkit/12.jpeg",
    "public/wedding-stories/Samkit/13.jpeg",
    "public/wedding-stories/Samkit/14.jpeg",
    "public/wedding-stories/Samkit/15.jpeg",
    "public/wedding-stories/Samkit/16.jpeg",
    "public/wedding-stories/Samkit/17.jpeg",
    "public/wedding-stories/Samkit/18.jpeg",
    "public/wedding-stories/Samkit/19.jpeg",
    "public/wedding-stories/Samkit/2.jpeg",
    "public/wedding-stories/Samkit/20.jpeg",
    "public/wedding-stories/Samkit/21.jpeg",
    "public/wedding-stories/Samkit/22.jpeg",
    "public/wedding-stories/Samkit/23.jpeg",
    "public/wedding-stories/Samkit/24.jpeg",
    "public/wedding-stories/Samkit/25.jpeg",
    "public/wedding-stories/Samkit/26.jpeg",
    "public/wedding-stories/Samkit/27.jpeg",
    "public/wedding-stories/Samkit/28.jpeg",
    "public/wedding-stories/Samkit/29.jpeg",
    "public/wedding-stories/Samkit/3.jpeg",
    "public/wedding-stories/Samkit/30.jpeg",
    "public/wedding-stories/Samkit/31.jpeg",
    "public/wedding-stories/Samkit/32.jpeg",
    "public/wedding-stories/Samkit/33.jpeg",
    "public/wedding-stories/Samkit/34.jpeg",
    "public/wedding-stories/Samkit/35.jpeg",
    "public/wedding-stories/Samkit/36.jpeg",
    "public/wedding-stories/Samkit/4.jpeg",
    "public/wedding-stories/Samkit/5.jpeg",
    "public/wedding-stories/Samkit/6.jpeg",
    "public/wedding-stories/Samkit/7.jpeg",
    "public/wedding-stories/Samkit/8.jpeg",
    "public/wedding-stories/Samkit/9.jpeg"
  ],
  "Shikha": [
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_01.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_02.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_03.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_04.jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(1).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(10).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(11).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(12).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(13).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(2).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(3).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(4).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(5).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(6).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(7).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(8).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(9).jpeg"
  ],
  "vaibhav-bhawna": [
    "public/wedding-stories/vaibhav-bhawna/1.jpeg",
    "public/wedding-stories/vaibhav-bhawna/11.jpeg",
    "public/wedding-stories/vaibhav-bhawna/12.jpeg",
    "public/wedding-stories/vaibhav-bhawna/13.jpeg",
    "public/wedding-stories/vaibhav-bhawna/14.jpeg",
    "public/wedding-stories/vaibhav-bhawna/15.jpeg",
    "public/wedding-stories/vaibhav-bhawna/16.jpeg",
    "public/wedding-stories/vaibhav-bhawna/17.jpeg",
    "public/wedding-stories/vaibhav-bhawna/18.jpeg",
    "public/wedding-stories/vaibhav-bhawna/19.jpeg",
    "public/wedding-stories/vaibhav-bhawna/2.jpeg",
    "public/wedding-stories/vaibhav-bhawna/20.jpeg",
    "public/wedding-stories/vaibhav-bhawna/21.jpeg",
    "public/wedding-stories/vaibhav-bhawna/22.jpeg",
    "public/wedding-stories/vaibhav-bhawna/23.jpeg",
    "public/wedding-stories/vaibhav-bhawna/24.jpeg",
    "public/wedding-stories/vaibhav-bhawna/25.jpeg",
    "public/wedding-stories/vaibhav-bhawna/26.jpeg",
    "public/wedding-stories/vaibhav-bhawna/27.jpeg",
    "public/wedding-stories/vaibhav-bhawna/28.jpeg",
    "public/wedding-stories/vaibhav-bhawna/29.jpeg",
    "public/wedding-stories/vaibhav-bhawna/3.jpeg",
    "public/wedding-stories/vaibhav-bhawna/4.jpeg",
    "public/wedding-stories/vaibhav-bhawna/5.jpeg",
    "public/wedding-stories/vaibhav-bhawna/6.jpeg"
  ]
};

const storiesData = [
  {
    id: 'akshita-sourav',
    slug: 'akshita-sourav',
    type: 'wedding',
    coupleName: 'Akshita & Sourav',
    location: 'Hisar, India',
    date: 'Winter 2024',
    heroImage: 'public/wedding-stories/Akshita-sourav/images%202/Wed_01.jpeg',
    excerpt: 'Three days of haldi hues, baraat energy, and regal pheras captured across Hisar.',
    fullStory: 'Akshita and Sourav celebrated every ritual with contagious joy. From turmeric drenched haldi frames to an opulent wedding night, their story is a timeless tribute to Punjabi grandeur.',
    images: storyImageMap['Akshita-sourav'],
  },
  {
    id: 'malkit-harman',
    slug: 'malkit-harman',
    type: 'wedding',
    coupleName: 'Malkit & Harman',
    location: 'Ludhiana, Punjab',
    date: 'Autumn 2024',
    heroImage: 'public/wedding-stories/malkit-harman/01.jpeg',
    excerpt: 'Classic Sikh traditions with modern styling, set inside a candle-lit gurudwara.',
    fullStory: 'Malkit and Harman trusted us to document each emotion—from quiet ardaas moments to their explosive dance floor. The result is a visual diary overflowing with warmth and metallic hues.',
    images: storyImageMap['malkit-harman'],
  },
  {
    id: 'partham-tamanna',
    slug: 'partham-tamanna',
    type: 'wedding',
    coupleName: 'Partham & Tamanna',
    location: 'Gurugram, India',
    date: 'Monsoon 2024',
    heroImage: 'public/wedding-stories/partham-tamanna/1.jpeg',
    excerpt: 'A pastel-soaked cocktail night that led straight into an effervescent wedding day.',
    fullStory: 'Urban luxury met heartfelt rituals for Partham and Tamanna. Every event transitioned seamlessly—sangeet, pheras, and vidaai—while we crafted layered visuals around their chemistry.',
    images: storyImageMap['partham-tamanna'],
  },
  {
    id: 'punit-varsha',
    slug: 'punit-varsha',
    type: 'wedding',
    coupleName: 'Punit & Varsha',
    location: 'Jaipur, Rajasthan',
    date: 'Summer 2024',
    heroImage: 'public/wedding-stories/punit-varsha/PV%20(1).jpeg',
    excerpt: 'Intimate palace nuptials with champagne-toned decor and dancing till dawn.',
    fullStory: 'Punit and Varsha\'s guest list was small but the emotions were colossal. We focused on quiet in-between moments, dreamy couple portraits, and every sparkle from their rooftop reception.',
    images: storyImageMap['punit-varsha'],
  },
  {
    id: 'samkit-naina',
    slug: 'samkit-naina',
    type: 'wedding',
    coupleName: 'Samkit & Naina',
    location: 'New Delhi, India',
    date: 'Spring 2024',
    heroImage: 'public/wedding-stories/Samkit/1.jpeg',
    excerpt: 'A sundowner pheras ceremony overlooking the city skyline and drenched in floral pastels.',
    fullStory: 'Samkit and Naina\'s celebrations flowed from choreographed sangeet acts to an airy mandap filled with baby\'s breath. We leaned into candid framing and cinematic silhouettes.',
    images: storyImageMap['Samkit'],
  },
  {
    id: 'shikha-sarthak',
    slug: 'shikha-sarthak',
    type: 'wedding',
    coupleName: 'Shikha & Sarthak',
    location: 'Chandigarh, India',
    date: 'February 2025',
    heroImage: 'public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(1).jpeg',
    excerpt: 'Velvet lehengas, mirror-work sherwanis, and a baraat that lit up the entire sector.',
    fullStory: 'Shikha and Sarthak wanted a fashion-forward wedding story. We paired editorial lighting with documentary coverage to showcase their statement outfits and heartfelt rituals.',
    images: storyImageMap['Shikha'],
  },
  {
    id: 'vaibhav-bhawna',
    slug: 'vaibhav-bhawna',
    type: 'wedding',
    coupleName: 'Vaibhav & Bhawna',
    location: 'Hisar, India',
    date: 'January 2025',
    heroImage: 'public/wedding-stories/vaibhav-bhawna/1.jpeg',
    excerpt: 'A cosy hometown wedding overflowing with family rituals, laughter, and dhol beats.',
    fullStory: 'Vaibhav and Bhawna kept each function rooted in tradition. We photographed every blessing, every sibling prank, and every tender glance that made their wedding unforgettable.',
    images: storyImageMap['vaibhav-bhawna'],
  }
];

function getStoryBySlug(slug) {
  return storiesData.find(story => story.slug === slug);
}

function getStoriesByType(type = 'all') {
  if (type === 'all') return storiesData;
  return storiesData.filter(story => story.type === type);
}

if (typeof window !== 'undefined') {
  window.storiesData = storiesData;
  window.getStoryBySlug = getStoryBySlug;
  window.getStoriesByType = getStoriesByType;
}
